### ISSUE TITLE
Add a non-root user

### ISSUE THREAD

**Issue by markjolah** [JCSDA/docker_base#14]
Is it possible to add a non-root user to the container (perhaps user: jcsda)?

It seems it is necessary to have a non-root user to run mpiexec.

This would make it easier to test the docker builds independently of singularity/charliecloud.  At the moment I have to manually add a new user to test.

This may also fix some of the issues that Maryam is having with permissions on Travis when using the docker.

I can probably do the PR if there are no technical considerations preventing this.  (I am new to docker)

**Comment by mer-a-o** [comment]
You need to change the user from root to be able to run mpi in Docker container. In ```Dockerfile```, I added jcsdauser to the docker image I build on Travis-ci server.

**Comment by mmiesch** [comment]
Thanks @markjolah - I normally don't do much testing in the docker container - rather, I build a Charliecloud or Singularity container and test there.   Still, this could be useful.  We could add a user as @mer-a-o has done, e.g. here: https://github.com/JCSDA/oops/blob/develop/Dockerfile
 But, am I understanding this file correctly that to run mpi you have to change the ownership of /usr/local to be jcsdauser?  This could have adverse consequences when building the Singularity and Charlicloud containers - I'm not sure.

**Comment by markjolah** [comment]
No, the chown and chmod and some of the related commands in: https://github.com/JCSDA/oops/blob/develop/Dockerfile
are not actually required to download build and test directly in the docker images.  All that is required is that the building of the bundle and the running of the tests is performed by the same non-root user.

I have realized that this issue is larger than just the non-root user and will attempt to merge it with my new issue: [docker_base #15](https://github.com/JCSDA/docker_base/issues/15)

**Comment by markjolah** [comment]
Merge this issue with [docker_base #15](https://github.com/JCSDA/docker_base/issues/15)
