### ISSUE TITLE
MPI read errors for fv3-bundle tests in Docker containers based on hpccm docker_base

### ISSUE THREAD

**Issue by markjolah** [JCSDA/docker_base#16]
Running the fv3-bundle tests under a hppcm docker_base container I'm getting many MPI? related error messages.
Running for instance: 
```
ctest -VV -R test_fv3jedi_hyb4dvar_geos
```
I get many hundreds of lines like this, even though the test does pass
```
343: [e18413f6edfd:25847] Read -1, expected 20736, errno = 1
```
These errors are not present on amazon jedi-stack-v3 AMI images.

Incidently, the test `test_fv3jedi_hyb4dvar_gfs` is failing in both old and new docker images and on jedi-stack AMI images.  I can get it to pass on my laptop.  The success/failure of this test doesn't seem to directly correlate to the use of hpccm base, but when running in the hpccm environment I get the same sorts of MPI read error messages.

_Originally posted by @markjolah in https://github.com/JCSDA/docker_base/pull/13#issuecomment-504223835_

**Comment by mmiesch** [comment]
@markjolah - has this problem been solved?  The gnu docker container for Travis and AWS CodeBuild seems to be fine.  The intel docker container has issues but not related to this.
